In [ ]:
Control Flow
If condition
a=int(input())
b=int(input())
if a>b:
    print(a)
if b>a:
    print(b)
Else condition.
a=int(input())
b=int(input())
if a>b:
    print(a)
else:
    print(b)
190
876
876
a=int(input())
b=int(input())
if a>b:
    print(a)
    print("if part")
else:
    print(b)
    print("else part")
a=int(input())
b=int(input())
if a>b:
    print(a)
    print("if part")
else:
    print(b)
    print("else part")
109
109
109
else part
If-Elif-Else Condition
a=int(input())
b=int(input())
if b>a:
    print(b)
elif a==b:
    print(a==b)
else:
    print(a)
13
13
True
x=11
y=9
if y==x:
    print("X")
elif y>x:
    print("Y")
else:
    print("X")
X

In [14]:
a=int(input("Enter Marks:"))
if a>=85:
    print(" A Grade ")
elif (a<85) and (a>=80):
            print( "A- Grade")
elif a<80 or a>=75:
         print("B Grade")

Enter Marks : 70


A- Grade


In [ ]:
elif a<80 or a>=75:
      print("B Grade")
elif a<75 or a>=70:
    print( "B- Grade")
elif a<70 or a>=60

In [2]:
x=int(input("Enter Marks :"))
if x>=85:
    print("A Grade")
elif x<85 and x>=80:
    print("A- Grade")
elif x<80 and x>=75:
    print("B grade")
elif x<75 and x>=70:
    print( "B- Grade")
elif x<70 and x>=65:
    print("C Grade")
elif x<65 and x>=60:
    print("Gharq")
elif x<60 and x>=50:
    print("Dazedalai")
else:
    print("Tabah")

Enter Marks :23
Tabah


In [1]:
x=float(input("Enter Real number:"))
y=round(x)
if x<0:
      if x>y:
        integer_portion=y+1
else:
    integer_portion=y
print(integer_portion)


# In[45]:


x=float(input("Enter Real number:"))
y=round(x)
if x<0:
      if x>y:
        integer_portion=y+1
else:
    integer_portion=y
print(integer_portion)

Enter Real number:-7.89
-7
Enter Real number:9.89
10


In [ ]:
x=float(input("Enter Real number:"))
y=round(x)
if x<0:
      if x>y:
        integer_portion=y-1
else:
    integer_portion=y
print(integer_portion)
if x<0:
    if x>y:
         integer_portion=y+1
    print(integer_portion)
else:
    integer_portion=y
print(integer_portion)

In [21]:
x=float(input("Enter Real number:"))
y=round(x)
if x>0:
      if x<y:
            integer_portion=y-1
else:
            integer_portion=y
print(integer_portion)
if x<0:
     if x>y:
        integer_portion=y+1
        print(integer_portion)
else:
        integer_portion=y
print(integer_portion)

Enter Real number:-76.87
-77
-76
-76


In [27]:
x=float(input("Enter Real number:"))
y=round(x)
if x>0:
    if x<y:
        intportion=y-1
    else:
        intportion=y
else:
    if y<x:
        intportion=y+1
    else:
        intportion=y
print(intportion)
if intportion%2==0:
    print("Even")
else:
    print("Odd")

Enter Real number:10.1
10
Even


# Loops

In [5]:
n=int(input("Enter the no iteration:"))
i=1
while i<=n:
    print(i**3)
    print("This is the iteration number:", i)
    i+=1
print(" We are done")

Enter the no iteration:0
 We are done


In [3]:
m=float(input("Enter a real number:"))
i=0
while i<m*2:
    print((i+2)**2)
    print(" This is the iteration:", i)
    i=i+1
    print("We are done")

Enter a real number:0


In [3]:
t=int(input("Enter an integer:"))
i=1
if i%2==0:
         print("break")
while i<t:
    print(i**2)
    print("This is the iteration:", i)
    i=i+3
    print("Done")

Enter an integer: 10


1
This is the iteration: 1
Done
16
This is the iteration: 4
Done
49
This is the iteration: 7
Done


In [2]:
n=int(input("Max iteration :"))
i=1
if i%4==0:
        print(i)
while i<n:
    i+=1
print("Done")

Max iteration : 10


Done


In [6]:
x_1=int(10)

In [7]:
x_1

10

In [10]:
x_1=x_1+1
print(x_1)

13


In [13]:
x_1+=1
print(x_1)

16


In [17]:
import pi from math
pi=3.1416

SyntaxError: invalid syntax (<ipython-input-17-0e18da5e10b3>, line 1)

In [18]:
x2=8.

In [19]:
type(x2)

float

In [23]:
current_year=2021

In [24]:
float(current_year)

2021.0

In [31]:
x=float(input("Enter Real number:"))
y=int(x)
print(y)
if y%2==0:
    print("Even")
else:
    print("Odd")

Enter Real number: -12.8


-12
Even


In [32]:
type(3.5//2)

float

In [33]:
5+True+True

7

In [34]:
6-False-True

5

In [35]:
True*7

7

In [36]:
True**10

1

In [37]:
False*9

0

In [38]:
bool(7)

True

In [39]:
bool(0)

False

In [40]:
bool("year")

True

In [41]:
bool(set())

False

### Anything with null, empty, something with 0 value converted to false by bool fun.

#### None is used for the missing value it maybe used to declare a variable whose value may be assigned later.

In [42]:
nothing= None
type(nothing)

NoneType

In [44]:
today="Tuesday"
today[0]

'T'

In [45]:
today[6]

'y'

In [46]:
today[3]

's'

In [47]:
today[2:6]

'esda'

In [48]:
"fun" in today

False

In [49]:
"day" in today

True

In [50]:
"tue" in today

False

In [51]:
"Tue" in today

True

In [61]:
fn="Mr Negative"
gr=" Assalamu-alekum  "

In [62]:
fn  +  gr

'Mr Negative Assalamu-alekum  '

In [63]:
fn + "" + gr + "!"

'Mr Negative Assalamu-alekum  !'

#### " " is used as a space while combining two strings.

In [64]:
today.lower()

'tuesday'

In [65]:
"tuesday".upper()

'TUESDAY'

In [4]:
today="Tuesday"

In [5]:
nd=today.replace("Tues", "Wednes")

In [6]:
nd

'Wednesday'

In [8]:
type(nd)

str

In [15]:
week=["Sun", "Mon", "Tues", "Wednes", "Thurs", "Fri", "Sat"]
day=["day", "day", "day", "day", "day","day", "day"]
ex=week+day

In [22]:
week[0:6]+day[0:6]

['Sun',
 'Mon',
 'Tues',
 'Wednes',
 'Thurs',
 'Fri',
 'day',
 'day',
 'day',
 'day',
 'day',
 'day']

In [9]:
"Sun, Mon, Tues, Wednes, Thurs, Fri, Sat".split(",")

['Sun', ' Mon', ' Tues', ' Wednes', ' Thurs', ' Fri', ' Sat']

In [28]:
day="day  "*7
print(day)

day  day  day  day  day  day  day  


In [30]:
print(list(day))

['d', 'a', 'y', ' ', ' ', 'd', 'a', 'y', ' ', ' ', 'd', 'a', 'y', ' ', ' ', 'd', 'a', 'y', ' ', ' ', 'd', 'a', 'y', ' ', ' ', 'd', 'a', 'y', ' ', ' ', 'd', 'a', 'y', ' ', ' ']


In [31]:
day=day  day  day  day  day  day  day

In [38]:
day.split(" k ")

['day, day, day, day, day ,day ,day ']

In [11]:
output_template="""If a grocery store sells ice bags at $ {} per bag, with the profit margin of $ {}, then the total profit it makes by selling {} ice bags is $ {}."""

In [17]:
cp=1.35
prm=0.25
noofbags=int(input(" Enter an integer:"))
tpr=cp*prm*noofbags
output_message=output_template.format(cp, prm*100, noofbags, tpr )
print(output_message)

 Enter an integer: 90


If a grocery store sells ice bags at $ 1.35 per bag, with the profit margin of $ 25.0, then the total profit it makes by selling 90 ice bags is $ 30.375000000000004.


In [16]:
output_message=output_template.format(cp, prm*100, noofbags, tpr )
print(output_message)

If a grocery store sells ice bags at $ 1.35 per bag, with the profit margin of $ 25.0, then the total profit it makes by selling 78 ice bags is $ 26.325000000000003.


In [7]:
new_template="If we sell ice bags at the price of $ {} per bag, with profit margin of {} %, then the total profit by selling {} bags is $ {}."""

In [8]:
cp=1.35
prm=0.25
noofbags=int(input(" Enter an integer:"))
tpr=cp*prm*noofbags
output_message= new_template.format(cp, prm*100, noofbags, tpr )
print(output_message)

 Enter an integer:89
If we sell ice bags at the price of $ 1.35 per bag, with profit margin of 25.0 %, then the total profit by selling 89 bags is $ 30.0375.


In [47]:
"If we sell ice bags at the price of per bag  $ " + str(cp) +",  with profit margin of   % " + str(prm) +" then by selling equals to " + str(noofbags)+" the total profit is:" + str(tpr)

'If we sell ice bags at the price of per bag  $ 1.35,  with profit margin of   % 0.25 then by selling equals to 98 the total profit is:33.075'

In [53]:
cp=1.35
prm=0.25
noofbags=int(input(" No of bags:"))
tpr=cp*prm*noofbags
"If we sell an ice bag at the price of per bag  $ " + str(cp) +",  with profit margin of per bag  %" + str(prm) +" then by selling no of bags equals to " + str(noofbags)+" we get the total profit equals to:" + str(tpr)

 No of bags: 90


'If we sell an ice bag at the price of per bag  $ 1.35,  with profit margin of per bag  %0.25 then by selling no of bags equals to 90 we get the total profit equals to:30.375000000000004'

In [11]:
y_1= 2.54
prf=0.35
no_books=int(input("Enter no of books:"))
total=y_1*prf*no_books
print(total)

Enter no of books:87
77.34299999999999


In [31]:
t_template=""" If book seller sells at the price of $ {} per book, with profit of {} % per book, then by selling {} books he earns totalprofit equals $ {} """

In [32]:
y1= 3.12
prf=0.20
no_books=int(input("Enter no of books:"))
total=y1*prf*no_books
tf=t_template.format(y1, prf, no_books,total)
print(tf)

Enter no of books:876
 If book seller sells at the price of $ 3.12 per book, with profit of 0.2 % per book, then by selling 876 books he earns totalprofit equals $ 546.6240000000001 


In [33]:
y_1= 2.54
prf=0.20
no_books=int(input("Enter no of books:"))
total=y_1*prf*no_books
tf=t_template.format(y_1, prf*100, no_books,total)
print(tf)

Enter no of books:876
 If book seller sells at the price of $ 2.54 per book, with profit of 20.0 % per book, then by selling 876 books he earns totalprofit equals $ 445.008 


In [1]:
y_1= 2.54
prf=0.20
no_books=int(input("Enter no of books:"))
total=y_1*prf*no_books
"If we sell book at the price of per book  $ " + str(y_1) +",  with profit margin of per book  %" + str(prf) +" then by selling no of books equals to " + str(no_books)+" we get the total profit equals to:" + str(total)

Enter no of books: 87


'If we sell book at the price of per book  $ 2.54,  with profit margin of per book  %0.2 then by selling no of books equals to 87 we get the total profit equals to:44.196'

In [13]:
def multiply(a,b):
 return a*b

In [12]:
def multiply(a, b):
   return a * b

In [1]:
def sq(num):
    words = list(str(num)) # split the text
    for word in words:  # for each word in the line:
        print(int(word)**2, end="") # print the word

num = 2345
sq(num)

491625

# List

In [4]:
fruits=['banana','cherry', 'berry', 'dates', 'mango']

In [5]:
fruits

['banana', 'cherry', 'berry', 'dates', 'mango']

In [6]:
len(fruits)

5

In [15]:
fruits.append('orange')

In [16]:
fruits

['banana', 'cherry', 'berry', 'dates', 'mango', 'orange', 'orange', 'orange']

In [17]:
fruits.append('pineapple')

In [19]:
print(fruits)

['banana', 'cherry', 'berry', 'dates', 'mango', 'orange', 'orange', 'orange', 'pineapple']


In [20]:
fruits.pop(6)

'orange'

In [22]:
print(fruits)

['banana', 'cherry', 'berry', 'dates', 'mango', 'orange', 'orange', 'pineapple']


In [23]:
fruits[0]

'banana'

In [24]:
fruits[5]

'orange'

In [25]:
fruits[3]

'dates'

In [33]:
fruits.pop(5)

'orange'

### If want to know about the last element of the list by code list_name[-1].

In [34]:
print(fruits)

['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple']


In [37]:
fruits.append('orange')

In [38]:
print(fruits)

['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange']


In [39]:
fruits[-1]

'orange'

In [40]:
fruits[-6]

'cherry'

In [41]:
fruits[-9]

IndexError: list index out of range

In [43]:
fruits[7]

IndexError: list index out of range

In [44]:
a_list=[None, 67>=89, "AoA", fruits, 2.7]

In [45]:
print(a_list)

[None, False, 'AoA', ['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange'], 2.7]


In [46]:
len(a_list)

5

In [47]:
a_list[3:5]

[['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange'], 2.7]

In [48]:
a_list[1:9]

[False,
 'AoA',
 ['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange'],
 2.7]

In [49]:
a_list[4:10]

[2.7]

In [51]:
a_list[2:11]

['AoA',
 ['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange'],
 2.7]

In [52]:
a_list[2:]

['AoA',
 ['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange'],
 2.7]

In [53]:
a_list[3:]

[['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange'], 2.7]

In [54]:
a_list[:10]

[None,
 False,
 'AoA',
 ['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange'],
 2.7]

In [55]:
a_list[:4]

[None,
 False,
 'AoA',
 ['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange']]

In [56]:
a_list[-2:-7]

[]

In [57]:
a_list[-2:-6]

[]

In [58]:
a_list[-1:-5]

[]

In [61]:
a_list[2:-4]

[]

In [60]:
a_list[-5:-2]

[None, False, 'AoA']

In [62]:
a_list[-6:-1]

[None,
 False,
 'AoA',
 ['banana', 'cherry', 'berry', 'dates', 'mango', 'pineapple', 'orange']]

## List can be modify.

In [63]:
fruits[2]='blueberry'

In [64]:
print(fruits)

['banana', 'cherry', 'blueberry', 'dates', 'mango', 'pineapple', 'orange']


In [65]:
fruits.insert(2, "apple")

In [66]:
print(fruits)

['banana', 'cherry', 'apple', 'blueberry', 'dates', 'mango', 'pineapple', 'orange']


In [68]:
fruits.append('cake')

In [69]:
fruits.remove('cake')

In [70]:
fruits

['banana',
 'cherry',
 'apple',
 'blueberry',
 'dates',
 'mango',
 'pineapple',
 'orange']

In [71]:
fruits.insert(-1, 'cake')

In [72]:
print(fruits)

['banana', 'cherry', 'apple', 'blueberry', 'dates', 'mango', 'pineapple', 'cake', 'orange']


In [73]:
fruits.pop(7)

'cake'

In [74]:
print(fruits)

['banana', 'cherry', 'apple', 'blueberry', 'dates', 'mango', 'pineapple', 'orange']


In [75]:
pineapple in fruits

NameError: name 'pineapple' is not defined

In [76]:
'pineapple' in fruits

True

In [77]:
'cake' in fruits

False

In [78]:
'cherry' in fruits

True

In [86]:
m_list=fruits + ['guava', 'potato'] + ['tomato' ,'chilli']

In [87]:
print(m_list)

['banana', 'cherry', 'apple', 'blueberry', 'dates', 'mango', 'pineapple', 'orange', 'guava', 'potato', 'tomato', 'chilli']


In [89]:
m_list.copy()

['banana',
 'cherry',
 'apple',
 'blueberry',
 'dates',
 'mango',
 'pineapple',
 'orange',
 'guava',
 'potato',
 'tomato',
 'chilli']

In [90]:
print(m_list.copy)

<built-in method copy of list object at 0x000002061BBC3400>


## Tuple 

In [91]:
frt=('apple', 'cherry', 'dates')

In [92]:
len(frt)

3

In [93]:
frt[0]

'apple'

In [94]:
frt[2]

'dates'

In [95]:
frt[-1]

'dates'

In [96]:
frt.append('avocado')

AttributeError: 'tuple' object has no attribute 'append'

In [97]:
frt.remove('apple')

AttributeError: 'tuple' object has no attribute 'remove'

#### We use list when want modification later on because list can be modify while tuple cannot be modify and remain unchanged.

In [102]:
single=6,

### Tuple are often used to create multiple variables with a single statement.

In [104]:
point=(-3,7)

In [105]:
point_x, point_y=point

In [106]:
point_x

-3

In [107]:
point_y

7

### Tuple can be converted into list and vice versa.

In [110]:
create=tuple(fruits)

In [111]:
print(create)

('banana', 'cherry', 'apple', 'blueberry', 'dates', 'mango', 'pineapple', 'orange')


In [114]:
back=list(create)

In [115]:
print(back)

['banana', 'cherry', 'apple', 'blueberry', 'dates', 'mango', 'pineapple', 'orange']


In [116]:
back==fruits

True

# Dictionary

In [118]:
persn1={
    'name': 'Irfan Marwat',
    'sex' : 'Male',
    'age' : '30',
    'married': True
}

In [119]:
persn1

{'name': 'Irfan Marwat', 'sex': 'Male', 'age': '30', 'married': True}

In [120]:
type(persn1)

dict

In [121]:
persn2=dict(name='Musibat Khan', sex='Female', age=23, married=False)

In [122]:
persn2

{'name': 'Musibat Khan', 'sex': 'Female', 'age': 23, 'married': False}

In [124]:
persn1['name']

'Irfan Marwat'

In [125]:
persn2['married']

False

In [126]:
persn1['address']

KeyError: 'address'

In [127]:
persn1.get('address', 'Lakki Marwat')

'Lakki Marwat'

In [128]:
persn1

{'name': 'Irfan Marwat', 'sex': 'Male', 'age': '30', 'married': True}

In [129]:
'name' in persn1

True

In [130]:
'address' in persn1

False

In [131]:
persn2['married']=True

In [132]:
persn2

{'name': 'Musibat Khan', 'sex': 'Female', 'age': 23, 'married': True}

In [133]:
persn1['address']='Tajori, Penny Lane'

In [134]:
persn1

{'name': 'Irfan Marwat',
 'sex': 'Male',
 'age': '30',
 'married': True,
 'address': '1, Penny Lane'}

In [135]:
persn1.pop('address')

'1, Penny Lane'

In [136]:
print(persn1)

{'name': 'Irfan Marwat', 'sex': 'Male', 'age': '30', 'married': True}


In [7]:
ms="How you are. " *5

In [8]:
ms

'How you are. How you are. How you are. How you are. How you are. '

In [9]:
ms.count("are")

5

In [11]:
ms.find('r')

9

In [12]:
ms.count(".")

5

In [13]:
ms.split(".")

['How you are',
 ' How you are',
 ' How you are',
 ' How you are',
 ' How you are',
 ' ']

In [14]:
ns=" I dont like, amrood, kela and apple"

In [15]:
ns.split('.')

[' I dont like, amrood, kela and apple']

In [3]:
def add_12(x):
    return x+12

In [5]:
add_12(12)

24

In [8]:
def multiply(a,b):
    return a+b

In [9]:
multiply(10,3)

13

In [10]:
multiply(234, 1976)

2210

In [14]:
def multiply(a,b,c,d):
    return (a*b*c-d)

In [15]:
multiply(12, 24, 89, 5)

25627

In [24]:
def even_odd(z):
    if z%2==0:
        print( Z,  'is even')
    else:
        print(z, 'is odd')

In [25]:
even_odd(1347)

1347 is odd


### lambda is a pre defined function in python which works with other functions combinely.

In [26]:
h=lambda x:x**3
h(123)

1860867

In [1]:
fl1=lambda x,y: x+y
fl1(2,3)

5

In [5]:
fl2=lambda x,y:x**2+y**2
fl2(3,5)

34

In [14]:
fl3=lambda x,y:(x**3+y**2+124)
fl2(13,5)

194

In [15]:
l1=[23, -24, 8,13, 98, 567, 134, 765, 33, 357, 21, 35, 102, 356]

In [18]:
ml1=list(filter(lambda x: (x%2==0),l1))

In [19]:
ml1

[-24, 8, 98, 134, 102, 356]

In [21]:
ml12=list(filter(lambda y: (y%2!=0),l1))

In [23]:
ml12

[23, 13, 567, 765, 33, 357, 21, 35]

In [24]:
l1

[23, -24, 8, 13, 98, 567, 134, 765, 33, 357, 21, 35, 102, 356]

#### lambda with map

In [34]:
ml13=list(map(lambda z: z**2, l1))

In [36]:
print(ml13)

[529, 576, 64, 169, 9604, 321489, 17956, 585225, 1089, 127449, 441, 1225, 10404, 126736]


In [37]:
from functools import reduce

In [39]:
smli=reduce(lambda x,y: x+y,l1)
smli

2488

# Object oriented programe

In [40]:
class phone:
    def make_Call(self):
        print('I am making a call')
    def play_game(self):
        print(' I am playing a game')

In [41]:
p1=phone()

In [42]:
p1.make_Call()

I am making a call


In [44]:
p1.play_game()

 I am playing a game


In [47]:
class phone:
    def set_color(self, color):
        self.color=color
    def set_cost(self, cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_Call(self):
        print('Make a call')
    def play_game(self):
        print('Play a game')

In [48]:
p2=phone()

In [49]:
p2.set_color('Red')

In [50]:
p2.set_cost(25000)

In [51]:
p2.show_color()

'Red'

In [52]:
p2.show_cost()

25000

In [54]:
p2.make_Call()

Make a call


In [56]:
p2.play_game()

Play a game


## Creating a class with Constructor

### Instantiating Object

In [57]:
class Employee:
    def __init__(self, name, age, salary, gender):
        self.name=name
        self.age=age
        self.salary=salary
        self.gender=gender
    def show_employee_details(self):
        print('Name of employee is', self.name)
        print('Age of employee is', self.age)
        print('Salary of employee is', self.salary)
        print('Gender of employee is', self.gender)

In [58]:
e1=Employee('Irfan', 30, 57000, 'Male')

In [61]:
e1.show_employee_details()

Name of employee is Irfan
Age of employee is 30
Salary of employee is 57000
Gender of employee is Male


### Inheritance in Python

In [63]:
class vehicle:
    def __init__(self, mileage, cost):
        self.mileage=mileage
        self.cost=cost
    def show_details(self):
        print(" I am a vehicle")
        print('Mileage of vehicle is', self.mileage)
        print('cost of vehicle is', self.cost)

In [64]:
v1=vehicle(1500, 45600)

In [65]:
v1.show_details()

 I am a vehicle
Mileage of vehicle is 1500
cost of vehicle is 45600


In [66]:
class car(vehicle):
    def show_car(self):
        print( 'I am a car')

In [67]:
c1=car(234, 145678)

In [68]:
c1.show_details()

 I am a vehicle
Mileage of vehicle is 234
cost of vehicle is 145678


In [69]:
c1.show_car()

I am a car


In [73]:
class car(vehicle):
    def __init__(self, mileage, cost, tyres, hp):
        super(). __init__(mileage, cost)
        self.tyres=tyres
        self.hp=hp
    def show_car_details(self):
        print( 'I am a car')
        print(' Tyres of car are', self.tyres)
        print('Hp of car is', self.hp)

In [74]:
c1=car(20,12000,4,300)

In [75]:
c1.show_car_details()

I am a car
 Tyres of car are 4
Hp of car is 300


In [76]:
c1.show_details()

 I am a vehicle
Mileage of vehicle is 20
cost of vehicle is 12000


# Numpy

In [77]:
import numpy as n
n1=n.array([1, 0, 45, 23])

In [79]:
n1

array([ 1,  0, 45, 23])

In [82]:
n2=n.array([[1, 2, 35, 6], [1, 7, 89, 0]])
n2

array([[ 1,  2, 35,  6],
       [ 1,  7, 89,  0]])

In [83]:
n3=n.array([[1, 2, 35, 6], [1, 7, 89, 0], [2, -20, 34, 67]])
n3

array([[  1,   2,  35,   6],
       [  1,   7,  89,   0],
       [  2, -20,  34,  67]])

In [85]:
n4=n.zeros((3,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
n5=n.full((4,3),8)
n5

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [87]:
n6=n.full((10,13),0)
n6

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [88]:
n7=n.zeros((10,13))
n7

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [89]:
n8=n.arange(10, 26)
n8

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [92]:
n9=n.arange(10,51,5)
n9

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [99]:
n12=n.arange(4, 780, 20)
n12

array([  4,  24,  44,  64,  84, 104, 124, 144, 164, 184, 204, 224, 244,
       264, 284, 304, 324, 344, 364, 384, 404, 424, 444, 464, 484, 504,
       524, 544, 564, 584, 604, 624, 644, 664, 684, 704, 724, 744, 764])

In [94]:
# need 5 random integers between 1 and 151

In [96]:
n10=n.random.randint(1,151, 5)
n10

array([ 72, 144, 132,  25,   5])

In [98]:
n11=n.random.randint(10, 1001, 25)
n11

array([ 28, 661, 106, 992, 848, 400, 579, 934, 839, 976, 985, 891, 616,
       494, 861, 462, 472, 282, 854, 101, 872,  18, 258, 540, 164])